# Generated by Django 5.1.2 on 2024-10-22 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food.order'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('no', 'no')], max_length=10),
        ),
    ]
