# Generated by Django 5.1.2 on 2024-10-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_orderitem_order_alter_productvariation_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
