# Generated by Django 5.1.2 on 2024-10-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'In Progress'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='In Progress', max_length=20),
        ),
    ]
